### ISSUE TITLE
gen_cov_file.sh How to change the thread

### ISSUE THREAD

**Issue by LiZhihua1982** [ziyewang/COMEBin#10]
(comebin_env) lizhihua@lizhihua-T640:/media/lizhihua/software/binning_method/COMEBin/COMEBin/scripts$ bash gen_cov_file.sh -a /media/lizhihua/data/LZLJ/GJ/GJ_all/final.contigs.fa -o /media/lizhihua/data/LZLJ/GJ/GJ_all/bamfiles /media/lizhihua/data/LZLJ/GJ/GJ_all/*.fastq -t 20

The thread is 20 but the result is -t 1 as below

[main] CMD: bwa mem -v 1 -t 1 /media/lizhihua/data/LZLJ/GJ/GJ_all/bamfiles/work_files/assembly.fa /media/lizhihua/data/LZLJ/GJ/GJ_all/GJall_1.fastq /media/lizhihua/data/LZLJ/GJ/GJ_all/GJall_2.fastq
[main] Real time: 108706.147 sec; CPU: 109901.352 sec

------------------------------------------------------------------------------------------------------------------------
-----                                       Sorting the GJall alignment file                                       -----
------------------------------------------------------------------------------------------------------------------------ 

[bam_sort_core] merging from 263 files and 1 in-memory blocks...

########################################################################################################################
########################################################################################################################

**Comment by ziyewang** [comment]
Hi，

Please input '-t 20' before specifying the path to '/media/lizhihua/data/LZLJ/GJ/GJ_all/*.fastq', and try it again.

For example, "bash gen_cov_file.sh -a /media/lizhihua/data/LZLJ/GJ/GJ_all/final.contigs.fa -t 20 -o /media/lizhihua/data/LZLJ/GJ/GJ_all/bamfiles /media/lizhihua/data/LZLJ/GJ/GJ_all/*.fastq"

Best,
Ziye
