### ISSUE TITLE
Thread usage in cluster.py

### ISSUE THREAD

**Issue by r-frizzo** [ziyewang/COMEBin#13]
Hello! I'm having an issue in the clustering step of version v1.0.4: 
Regardless of the value of -t, _cluster.py_ always uses all available CPUs.

We may have found the problem: 

In _cluster.py_:

line 66:     
`int_labels = p.add_items(features, labels_index)`

and line 398:        
`ann_neighbor_indices, ann_distances = p.knn_query(norm_embeddings, max_edges+1)`

both functions lack the argument _num_threads_, causing them to default to -1 (all available cores)

Hope this helps and thank you for the tool, I'm getting promising results!
Riccardo

**Comment by ziyewang** [comment]
Hi,

Thank you for helping us identify the issue with thread usage in the cluster.py file. I have made the modifications at the respective location.

Best,
Ziye
