### ISSUE TITLE
Parsing final output - is there any value in preclustered bins?

### ISSUE THREAD

**Issue by AaronAOliver** [ziyewang/COMEBin#14]
Hello folks,

Great tool so far, I appreciate the ease of use/install compared to the complexity of metaWRAP and DAS_tool dependencies.
I had a question about how to best parse the output of bins. Running the tool through a single sample, it looks like two folders of bins are created - `comebin_res_bins` and `cluster_res/$(best model name)_bins`

From what I can tell, the `comebin_res_bins` is the initial split of every contig such that all contigs are placed into some bin, while the `cluster_res` result only has some contigs placed into bins, based on your Leiden clustering. When I run the `comebin_res_bins` fastas through CheckM1 - I get 94 bins meeting 50% completeness, 10% contamination. But, I can see the CheckM1 output provided by combin for the `cluster_res` bins given in `cluster_res/unitem_profile`, which has only 30 clustered bins that reach > 50% complete, < 10% contaminated. The number of higher quality (90% complete, 5% contamination) bins is also higher noticably before clustering (33 vs. 16).

Is the clustering performing a dereplication function similar to [dRep](https://github.com/MrOlm/drep), where only the best bin from a kmer-coverage-similarity group is kept? I often use % nucleotides binned in medium-quality MAGs as a metric for evaluating binning software, so this difference (26% nucleotides binned after clustering vs. 56% nucleotides binned before clustering) jumped out at me. I can appreciate the value in having fewer, consolidated bins per predicted taxa, but I just wanted to confirm what this tool is doing before I move forward with any post processing of the MAGs.

Thanks for your help!

**Comment by ziyewang** [comment]
Hello, 

Thank you for using COMEBin. In fact, comebin_res_bins is the final output that can be used for subsequent analysis. The bins in cluster_res are intermediate results used only to obtain single-copy gene information for contigs and are not the final results. We didn't perform a dereplication function, and we only kept the bins larger than 200kbp.

Best,
Ziye
