### ISSUE TITLE
Is it for the individual-or co-  assembly?

### ISSUE THREAD

**Issue by B1991ing** [ziyewang/COMEBin#2]
Hi Ziye,

I am going to try the COMEBin v1.0.3 to bin my contigs, but is it for the individual-or co-  assembly?

Looking forward your reply.

Thank you very much.

Best,

Bing

**Comment by ziyewang** [comment]
Hi,

COMEBin can be applied for both individual (single-sample binning) and co-assembly binning.
For additional information, please refer to https://github.com/ziyewang/COMEBin_benchmark/tree/master/benchmark.

Best regards,
Ziye
