### ISSUE TITLE
Problems with augmented data

### ISSUE THREAD

**Issue by ttmgr** [ziyewang/COMEBin#3]
Hello! 
I wanted to use your tool on my sequencing data, but when I run run_comebin.sh I get this error message:

N50: 3523
Tau(temperature): 0.15
./processing/combined/data_augmentation does not exist.
Running data augmentation.
Something went wrong with running generating augmentation data. Exiting.

The first step, gen_cov_file.sh, gave me the following output:
assembly.fa
assembly.fa.bwt
filtered_barcode01_passed.bam
filtered_barcode11_passed.bam
filtered_barcode14_passed.bam
assembly.fa.amb
assembly.fa.pac
filtered_barcode06_passed.bam
filtered_barcode12_passed.bam
assembly.fa.ann  assembly.fa.sa
filtered_barcode07_passed.bam
filtered_barcode13_passed.bam

I am a bit lost! Thanks in advance :)

**Comment by ziyewang** [comment]
Hi, 
the issue may lie in the fact that the code changes the current path, so all paths in the run_comebin.sh options should be absolute. For example: -o /home/wzy/res.

Best wishes,
Ziye

**Comment by ttmgr** [comment]
Thanks for your quick help!
