### ISSUE TITLE
Single-copy maker genes for clustering 

### ISSUE THREAD

**Issue by timghaly** [ziyewang/COMEBin#6]
Hi this tool looks great, and am excited to give it a go. I'm just curious what set of marker genes are used in the final clustering step. I am interested in generating eukaryote MAGs, though. Are the markers prokaryote-specific and thus exclude any eukaryote bins from the final output?

**Comment by ziyewang** [comment]
Hi,

The marker genes are from bacterial and archaeal marker sets. While we assessed the quality of the Leiden results with various parameters, estimating completeness and contamination based on prokaryotic SCGs, COMEBin still manages to recover eukaryotic genomes.

While the genomes present in the datasets may originate from domains other than bacteria and archaea, we assume that the Leiden results performing well for bacterial and archaeal genomes are generally superior.

Best,
Ziye

**Comment by timghaly** [comment]
Okay, thanks for that clarification Ziye. I will give it a go.

Best,
Tim
