### ISSUE TITLE
Using a coverage file generated using metabat2

### ISSUE THREAD

**Issue by adityabandla** [ziyewang/COMEBin#9]
Hello,

Thank you for this new tool. I was wondering if we can use the coverage table generated by METABAT2 directly with comebin, instead of generating a new one?

Cheers, Adi

**Comment by ziyewang** [comment]
Hello,

To utilize COMEBin, users are required to provide contigs along with BAM files. While you can utilize the BAM files utilized for creating coverage tables by MetaBAT2, you cannot directly employ the coverage table generated by MetaBAT2.

Thanks,
Ziye
